### ISSUE TITLE
Stubs loses "use" statements

### ISSUE THREAD

**Issue by andreasciamanna** [GiacoCorsiglia/php-stubs-generator#8]
Looking at its activities, I'm not sure if this project is still maintained.  
However, would still like to report an issue hoping for a fix :)

When exporting a class which has one or more "use" statements, these are not included in the stub.

This issue cases PHPStan to think that a returned value (which is the scope of the namespace of one of these "use" statements) is not defined.

In other words, this:

```php
namespace WPML\LIB\WP;

use WPML\FP\Either;
use WPML\FP\Promise;

class Hooks {

	/**
	 * @param string|string[] $action
	 * @param int             $priority
	 * @param int             $accepted_args
	 *
	 * @return Promise
	 */
	public static function onAction( $action, $priority = 10, $accepted_args = 1 ) {
		return self::onHook( 'add_action', $action, $priority, $accepted_args );
	}
```

Is stubbed as:

```php
namespace WPML\LIB\WP;

class Hooks {
    /**
     * @param string|string[] $action
     * @param int             $priority
     * @param int             $accepted_args
     *
     * @return Promise
     */
    public static function onAction($action, $priority = 10, $accepted_args = 1)
    {
    }
```

PHPStan, when validating the stub, shows `Return typehint of method WPML\LIB\WP\Hooks::onAction() has invalid type WPML\LIB\WP\Promise.` because it obviously assumes `Promise` is part of `\WPML\LIB\WP`.

Manually adding the missing "use" statements, the error goes away.

The problem is that I've hundred of stubs like these :(

**Comment by szepeviktor** [comment]
You should always typehint in phpdoc block with FQCN.

**Comment by andreasciamanna** [comment]
Right.

A rule I forgot. 

Thanks!

**Comment by mundschenk-at** [comment]
> You should always typehint in phpdoc block with FQCN.

Not actually true (anymore): https://docs.phpdoc.org/3.0/guide/guides/types.html

**Comment by szepeviktor** [comment]
It's not that it is not supported but highly misleading if you put only the last word from the FQCN in PHPDoc.
